# Generated by Django 4.2.10 on 2024-03-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='modification_allowed_until',
        ),
    ]
