# Generated by Django 4.2.10 on 2024-03-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_reservation_modification_allowed_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='dropoff_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
