# Generated by Django 4.2.10 on 2024-03-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_reservation_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='card_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmation_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
