# Generated by Django 4.2.11 on 2024-03-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reservation_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deposit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
