# Generated by Django 4.2.11 on 2024-03-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('is_electric', models.BooleanField(default=False)),
                ('is_all_wheel_drive', models.BooleanField(default=False)),
            ],
        ),
    ]
