# Generated by Django 4.2.10 on 2024-03-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(default="unknown", max_length=50)),
                ("model", models.CharField(default="unknown", max_length=50)),
                ("year", models.PositiveIntegerField(default=0)),
                ("price", models.PositiveIntegerField(default=0)),
                ("reserved", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        default="car_images/default.jpg", upload_to="car_images/"
                    ),
                ),
                ("mileage", models.PositiveIntegerField(default=0)),
                ("company_uuid", models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
