# Generated by Django 4.2.11 on 2024-03-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='company',
        ),
        migrations.RemoveField(
            model_name='car',
            name='reserved',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='default_car_image.png', upload_to='car_images'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_all_wheel_drive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='is_electric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
