# Generated by Django 4.2.10 on 2024-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
